"""
    ELEXIS Protocol for accessing dictionaries

    This protocol allows data to be shared with the ELEXIS platform and should be implemented by all providers of data to the ELEXIS platform. This is an OpenAPI documentation, for more details about using this specification, please refer to OpenAPI documentations: https://swagger.io/resources/articles/documenting-apis-with-swagger/  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.ontolex_entry_canonical_form import OntolexEntryCanonicalForm
from openapi_client.model.ontolex_form import OntolexForm
from openapi_client.model.ontolex_lexical_sense import OntolexLexicalSense
globals()['OntolexEntryCanonicalForm'] = OntolexEntryCanonicalForm
globals()['OntolexForm'] = OntolexForm
globals()['OntolexLexicalSense'] = OntolexLexicalSense
from openapi_client.model.ontolex_entry import OntolexEntry


class TestOntolexEntry(unittest.TestCase):
    """OntolexEntry unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOntolexEntry(self):
        """Test OntolexEntry"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OntolexEntry()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
