"""
    ELEXIS Protocol for accessing dictionaries

    This protocol allows data to be shared with the ELEXIS platform and should be implemented by all providers of data to the ELEXIS platform. This is an OpenAPI documentation, for more details about using this specification, please refer to OpenAPI documentations: https://swagger.io/resources/articles/documenting-apis-with-swagger/  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.agent import Agent
from openapi_client.model.agent_class import AgentClass
from openapi_client.model.date_time import DateTime
globals()['Agent'] = Agent
globals()['AgentClass'] = AgentClass
globals()['DateTime'] = DateTime
from openapi_client.model.metadata import Metadata


class TestMetadata(unittest.TestCase):
    """Metadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMetadata(self):
        """Test Metadata"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Metadata()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
