"""
    ELEXIS Protocol for accessing dictionaries

    This protocol allows data to be shared with the ELEXIS platform and should be implemented by all providers of data to the ELEXIS platform. This is an OpenAPI documentation, for more details about using this specification, please refer to OpenAPI documentations: https://swagger.io/resources/articles/documenting-apis-with-swagger/  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from openapi_client.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)
from ..model_utils import OpenApiModel
from openapi_client.exceptions import ApiAttributeError


def lazy_import():
    from openapi_client.model.ontolex_entry_canonical_form import OntolexEntryCanonicalForm
    from openapi_client.model.ontolex_form import OntolexForm
    from openapi_client.model.ontolex_lexical_sense import OntolexLexicalSense
    globals()['OntolexEntryCanonicalForm'] = OntolexEntryCanonicalForm
    globals()['OntolexForm'] = OntolexForm
    globals()['OntolexLexicalSense'] = OntolexLexicalSense


class OntolexEntry(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('type',): {
            'LEXICALENTRY': "LexicalEntry",
            'WORD': "Word",
            'MULTIWORDEXPRESSION': "MultiWordExpression",
            'AFFIX': "Affix",
        },
        ('part_of_speech',): {
            'ADJECTIVE': "adjective",
            'ADPOSITION': "adposition",
            'ADVERB': "adverb",
            'AUXILIARY': "auxiliary",
            'COORDINATINGCONJUNCTION': "coordinatingConjunction",
            'DETERMINER': "determiner",
            'INTERJECTION': "interjection",
            'COMMONNOUN': "commonNoun",
            'NUMERAL': "numeral",
            'PARTICLE': "particle",
            'PROPERNOUN': "properNoun",
            'PUNCTUATION': "punctuation",
            'SUBORDINATINGCONJUNCTION': "subordinatingConjunction",
            'SYMBOL': "symbol",
            'VERB': "verb",
            'OTHER': "other",
        },
    }

    validations = {
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'context': (str,),  # noqa: E501
            'id': (str,),  # noqa: E501
            'type': (str,),  # noqa: E501
            'canonical_form': (OntolexEntryCanonicalForm,),  # noqa: E501
            'senses': ([OntolexLexicalSense],),  # noqa: E501
            'part_of_speech': (str,),  # noqa: E501
            'other_form': ([OntolexForm],),  # noqa: E501
            'morphological_pattern': (str,),  # noqa: E501
            'etymology': (str,),  # noqa: E501
            'usage': (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'context': '@context',  # noqa: E501
        'id': '@id',  # noqa: E501
        'type': '@type',  # noqa: E501
        'canonical_form': 'canonicalForm',  # noqa: E501
        'senses': 'senses',  # noqa: E501
        'part_of_speech': 'partOfSpeech',  # noqa: E501
        'other_form': 'otherForm',  # noqa: E501
        'morphological_pattern': 'morphologicalPattern',  # noqa: E501
        'etymology': 'etymology',  # noqa: E501
        'usage': 'usage',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, context, id, type, canonical_form, senses, *args, **kwargs):  # noqa: E501
        """OntolexEntry - a model defined in OpenAPI

        Args:
            context (str): The JSON-LD Context Document, which should be derived from the OntoLex JSON spec
            id (str): The identifier of this resource
            type (str): The type of this entry
            canonical_form (OntolexEntryCanonicalForm):
            senses ([OntolexLexicalSense]): The sense property relates a lexical entry to one of its lexical senses.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            part_of_speech (str): The part of speech of the entry. [optional]  # noqa: E501
            other_form ([OntolexForm]): The other form property relates a lexical entry to a non-preferred (\"non-lemma\") form that realizes the given lexical entry.. [optional]  # noqa: E501
            morphological_pattern (str): The morphological pattern property indicates the morphological class of a word.. [optional]  # noqa: E501
            etymology (str): The etymology of the entry. [optional]  # noqa: E501
            usage (str): The usage property indicates usage conditions or pragmatic implications when using the lexical entry to refer to the given ontological meaning.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.context = context
        self.id = id
        self.type = type
        self.canonical_form = canonical_form
        self.senses = senses
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, context, id, type, canonical_form, senses, *args, **kwargs):  # noqa: E501
        """OntolexEntry - a model defined in OpenAPI

        Args:
            context (str): The JSON-LD Context Document, which should be derived from the OntoLex JSON spec
            id (str): The identifier of this resource
            type (str): The type of this entry
            canonical_form (OntolexEntryCanonicalForm):
            senses ([OntolexLexicalSense]): The sense property relates a lexical entry to one of its lexical senses.

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            part_of_speech (str): The part of speech of the entry. [optional]  # noqa: E501
            other_form ([OntolexForm]): The other form property relates a lexical entry to a non-preferred (\"non-lemma\") form that realizes the given lexical entry.. [optional]  # noqa: E501
            morphological_pattern (str): The morphological pattern property indicates the morphological class of a word.. [optional]  # noqa: E501
            etymology (str): The etymology of the entry. [optional]  # noqa: E501
            usage (str): The usage property indicates usage conditions or pragmatic implications when using the lexical entry to refer to the given ontological meaning.. [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.context = context
        self.id = id
        self.type = type
        self.canonical_form = canonical_form
        self.senses = senses
        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
